#! /bin/sh -e

case "$1" in
    purge)
	rm -f /etc/adjtimex.conf
	update-rc.d adjtimex remove >/dev/null
	;;
    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
	exit 0
	;;
    *)
	echo "postrm called with unknown argument \`$1'" >&2
	exit 0
	;;
esac

