#!/bin/sh

set -e

while true
do
	echo "Most system clocks are not really exact. Shall I adjust the system clock to"
	echo -n 'correct for systematic drift, using the CMOS clock as a reference? (y/n) [N] '
	read input
	if [ $input = "y" ]
	then
		cat << EOF
This configuration tool adjusts the kernel \`tick' and \`frequency'
variables, and resets those variables on every boot.

The adjustment might result in incorrect values on a heavily loaded system.
You can compare the system clock with the CMOS clock at any time with
\`/usr/sbin/adjtimex --compare'.  If they differ significantly please try
calling \`/usr/sbin/adjtimexconfig' to repeat the adjustment.  You can also
edit the output (/etc/rc.boot/adjtimex) manually at any time.

This will take about 1.5 minutes.

EOF
		/usr/sbin/adjtimexconfig
		sh /etc/rc.boot/adjtimex
		break
	else
		cat << EOF
This adjustment can be done at any time by calling \`/usr/sbin/adjtimexconfig'.
In particular, if you find the CMOS clock has a systematic drift, read the
clock(8) manual page, modify /etc/adjtime as required, and call
\`/usr/sbin/adjtimexconfig'.

EOF
		break
	fi 2>/dev/null
done

